export enum ActionTypes {
    FETCH_ALBUMS ='FETCH_ALBUMS',
    FETCH_API_AUTHOR_DETAILS = 'FETCH_API_AUTHOR_DETAILS',
    UPDATE_FAVORITE = 'UPDATE_FAVORITE',
    FILTER_ALBUMS = 'FILTER_ALBUMS',
    UPDATE_PAGE = 'UPDATE_PAGE'
}